version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: tring
    main: ./cmd/tring
    binary: tring
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X github.com/ystkfujii/tring/internal/version.Version={{.Version}}
      - -X github.com/ystkfujii/tring/internal/version.Commit={{.Commit}}
      - -X github.com/ystkfujii/tring/internal/version.Date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: ystkfujii
    name: tring
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
